### ISSUE TITLE
No SkyModel.Tools.PolygonTools

### ISSUE THREAD

**Issue by bennahugo** [cyriltasse/SkyModel#1]
@cyriltasse Did you forget to include the file above in your latest commit? My test cases on DDFacet are failing because of this. https://jenkins.meqtrees.net/job/ddfacet-pr-build/55/console

**Comment by bennahugo** [comment]
- 20:48:19 - ClassMS                   | [1m[91mCould not import lofar.stationresponse[0m[0m
- 20:48:19 - MyLogger                  | [1m[91mSet silent: ['NpShared'][0m[0m
- 20:48:19 - MyLogger                  | [1m[91mSet silent: MyLogger[0m[0m
  Traceback (most recent call last):
  File "/projects/DDFacet/DDF.py", line 13, in <module>
    from DDFacet.Imager import ClassDeconvMachine
  File "/projects/DDFacet/Imager/ClassDeconvMachine.py", line 1, in <module>
    from ClassFacetMachineTessel import ClassFacetMachineTessel as ClassFacetMachine
  File "/projects/DDFacet/Imager/ClassFacetMachineTessel.py", line 11, in <module>
    from SkyModel.Sky import ModVoronoi
  File "/projects/SkyModel/Sky/ModVoronoi.py", line 4, in <module>
    import SkyModel.Tools.PolygonTools as PT
  ImportError: No module named PolygonTools

**Comment by cyriltasse** [comment]
ok I've added PolygonTools

**Comment by bennahugo** [comment]
ok. I've added another job on the jenkins server to periodically test the master branch against the reference images generated earlier to catch this sort of thing. https://jenkins.meqtrees.net/job/DDFacet_master_cron/
